language: node_js
node_js: "12"

os: linux
dist: trusty

cache: npm

branches:
  only:
    - master

script:
  - npm ci
  - npx ng lint
  - npm run build:prod

deploy:
  provider: pages
  strategy: git
  token: $GITHUB_TOKEN
  local_dir: dist/deploy
  cleanup: false
  keep_history: true
  on:
    branch: master
