language: node_js
dist: trusty
node_js: "12"

cache: npm

branches:
  only:
    - master

script:
  - npm ci
  - npx ng lint
  - npm run build:prod

deploy:
  provider: pages
  local_dir: /dist/deploy
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
