name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 12.x

    - uses: actions/checkout@v2

    - name: Install
      run: npm ci
      
    - name: Lint
      run: npx ng lint
      
    - name: Build
      run: npm run build:prod

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/deploy
        cname: codecomet.io
      if: github.ref == 'refs/heads/master'
